### ISSUE TITLE
Validate function has no hb

### ISSUE THREAD

**Issue by bgoussen** [bgoussen/BeeGUTS#12]
At the moment, the validate function uses a default hb of 0. 
This is due to the fact that multiple background mortalities can be estimated during the calibration phase (one per dataset). 

The current prediction function used in the validation can only accomodate one hb. Using a default hb of 0 allows the validation function to work. In the future, it might be interesting to allow the user to define the hb to be used, to allow for using the calibrated hb if only one dataset was used for calibration, or to recalibrate hb for each validation dataset.

**Comment by Carlor87** [comment]
validation now includes handling of hb
